EASY-1411: introducing Scala 2.12
DANS-KNAW/dans-scala-lib pull request #12
Opened 2017-12-14 09:07 UTC by rvanheest

Fixes EASY-1411

@DANS-KNAW/easy for review

This is the first step into moving EASY's Scala modules from Scala 2.11 to 2.12. In order to make this switch, all dependencies must be compiled with Scala 2.12.

Until now, this library inherited from the `dans-prototype` parent-project, while at the same time `dans-prototype` also has a dependency on this library. To break this cyclic dependency, I removed the inheritance from `dans-prototype` and put the necessary plugins in this `pom.xml`.

Furthermore, to keep up with Scala conventions, I renamed the artifactId to `dans-scala-lib_2.12`.

### Special review request
@janvanmansum Please check extra if I didn't miss any Maven plugins (e.g. whether I copied everything correctly)

#### Next steps
* after review, merge this PR, #10, #11 and an additional PR by @janvanmansum 
* make a new release of this library **(please note: the artifactId changed!!!)**

2017-12-14 11:30 UTC, jo-pol commented on pom.xml
> +    <artifactId>dans-scala-lib_2.12</artifactId>
👍

2017-12-21 08:23 UTC, janvanmansum requested changes
Try to set `dans-prototype` as the parent. I think this will allow you to have a much smaller `pom.xml`, while still preventing the cyclic dependency.

2018-01-03 14:33 UTC, janvanmansum commented on src/test/scala/nl/knaw/dans/lib/error/CompositeExceptionSpec.scala
> +  "printStackTrace" should "include the messeges (and stacktraces) of all exceptions in the composite exception" in {
"messages"

2018-01-03 14:46 UTC, janvanmansum approved these changes

2018-01-03 14:46 UTC, merged